http:
  routers:
    uptime-kuma:
      rule: "Host(`status.yapserver.fr`)"
      entrypoints: [websecure]
      tls: {certResolver: cloudflare}
      middlewares: [internal-only@file]
      service: uptime-kuma-svc

  services:
    uptime-kuma-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.30.10:3001"
