all:
  children:
    proxmox:
      hosts:
        pve1: { ansible_host: 10.0.10.10 }
        pve2: { ansible_host: 10.0.10.11 }
        pve3: { ansible_host: 10.0.10.12 }
        pve4: { ansible_host: 10.0.10.13 }
    services:
      hosts:
        infra:      { ansible_host: 10.0.30.10 }
        monitoring: { ansible_host: 10.0.30.11 }
        cloud:      { ansible_host: 10.0.30.12 }
        media:      { ansible_host: 10.0.30.13 }
        security:   { ansible_host: 10.0.30.14 }
        scanner:    { ansible_host: 10.0.30.15 }
        firefly:    { ansible_host: 10.0.30.16 }
        osint:      { ansible_host: 10.0.30.17 }
        ir:         { ansible_host: 10.0.30.18 }
