services:
  app:
    image: fireflyiii/core:v6.6.3@sha256:4d63328dbc7c60ef5a8269bb2ee89f120b28f88eb0395e4211e23f93fd79337f   # épinglé version+digest (Renovate)
    restart: unless-stopped
    env_file: .env
    volumes: [ "upload:/var/www/html/storage/upload" ]
    ports: [ "8080:8080" ]
    depends_on: [ db ]
  db:
    image: mariadb:11.8.8@sha256:be1ef4fe5f14589325c08a41c76334097ce66c86264b75e1d28342c742782a61   # épinglé version+digest (Renovate)
    restart: unless-stopped
    env_file: .db.env
    volumes: [ "db:/var/lib/mysql" ]
  importer:
    image: fireflyiii/data-importer:v2.3.2@sha256:4e2cbcb0d95c34850534a3772f1732c00f6412077db33b1863703a1b628bdc12   # épinglé version+digest (Renovate)
    restart: unless-stopped
    env_file: .importer.env
    volumes: [ "./enablebanking.pem:/eb.pem:ro" ]
    ports: [ "8081:8080" ]
    depends_on: [ app ]
volumes: { upload: {}, db: {} }
